#!/bin/bash
programName="Discord"
programURL="https://discord.com/api/download?platform=linux&format=deb"
SERVER_VERSION=$(curl -sI "$programURL" | grep location: | awk -F'/discord-|.deb' '{print $2}')
LOCAL_VERSION=$(dpkg --list | grep discord | awk '{print $3}')

if [ "$LOCAL_VERSION" == "$SERVER_VERSION" ]; then
	echo "Latest version of $programName is already installed. Skipping..."
else
	wget "$programURL" -O "$programName"
	sudo dpkg -i "$programName"
	rm "$programName"
	sudo dpkg --configure -a
	echo "$programName has been installed/updated."
fi
