#!/bin/bash

# Variables
CODE_URL="https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
CODE_SERVER_VERSION=$(curl -sI "$CODE_URL" | grep location: | awk -F'/code_' '{print $2}' | awk -F'-' '{print $1}')
CODE_FILE="CODE_$CODE_SERVER_VERSION"
CODE_LOCAL_VERSION=$(dpkg --list | grep code | awk '{print $3}')

# Check if Update is needed
if [ "$CODE_SERVER_VERSION" == "$CODE_LOCAL_VERSION" ]; then
    echo "The latest version of VS Code is installed. Skipping."
    exit 0
fi

echo "VS Code update found. Downloading update..."
wget -q -O "/tmp/$CODE_FILE" "$CODE_URL"
echo "Update downloaded. Installing..."
sudo dpkg -i "/tmp/$CODE_FILE"
echo "Update installed."
rm "/tmp/$CODE_FILE"
sudo dpkg --configure -a
