#!/bin/bash

# Standard APT Update Commands
apt update
apt full-upgrade -y
apt autoremove -y

# Checks other programs for updates
if command -v fwupdmgr >/dev/null 2>&1; then
    fwupdmgr update -y
else
    echo "fwupd not installed. Skipping..."
fi

if command -v flatpak >/dev/null 2>&1; then
    flatpak update -y
else
    echo "Flatpak not installed. Skipping..."
fi

if command -v snap >/dev/null 2>&1; then
    snap refresh
else
    echo "Snap not installed. Skipping..."
fi

# The update folder contains packages that need manual deb installs
find update/. -type f -exec {} \;